[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_dice_2024 = "J86V1Echaw6CB1aMbGVbmgCb37RUBcev9QmruuR91mma"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
